# biosdevname
# Autogenerated from man page /usr/share/man/man1/biosdevname.1.gz
complete -c biosdevname -s i -l interface -d 'Treat [args] as ethernet devs'
complete -c biosdevname -s d -l debug -d 'Enable debugging'
complete -c biosdevname -s P -l prefix -d 'string use for embedded NICs in the physical policy (default=em)'
complete -c biosdevname -s x -l nopirq -d 'Do not use $PIR table for mapping PCI device to slot'
complete -c biosdevname -s p -l policy
complete -c biosdevname -s s -l smbios -d 'Require minimum SMBIOS version x. y POLICIES'

