# compel
# Autogenerated from man page /usr/share/man/man1/compel.1.gz
complete -c compel -s f -l file
complete -c compel -s o -l output
complete -c compel -s p -l prefix
complete -c compel -s l -l log-level
complete -c compel -s h -l help
complete -c compel -s V -l version

