# grub2-probe
# Autogenerated from man page /usr/share/man/man8/grub2-probe.8.gz
complete -c grub2-probe -l device -d 'Final option represents a DEVICE, rather than a filesystem PATH'
complete -c grub2-probe -l device-map -d 'Use FILE as the device map.   The default value is /boot/grub/device. map'
complete -c grub2-probe -l target -d 'Select among various output definitions.   The default is fs. RS'
complete -c grub2-probe -l verbose -d 'Print verbose output'

