# grub2-set-password
# Autogenerated from man page /usr/share/man/man8/grub2-set-password.8.gz
complete -c grub2-set-password -s h -l help -d 'Display program usage and exit'
complete -c grub2-set-password -s v -l version -d 'Display the current version'
complete -c grub2-set-password -s o -l output -d 'Choose the file path to which user. cfg will be written'

