# grub2-mklayout
# Autogenerated from man page /usr/share/man/man1/grub2-mklayout.1.gz
complete -c grub2-mklayout -l input -d 'Use FILE as the input.   The default value is the standard input device'
complete -c grub2-mklayout -l output -d 'Use FILE as the output.   The default value is the standard output device'
complete -c grub2-mklayout -l verbose -d 'Print verbose messages'

