# grub2-mkstandalone
# Autogenerated from man page /usr/share/man/man1/grub2-mkstandalone.1.gz
complete -c grub2-mkstandalone -l output -d 'Write the generated file to FILE'
complete -c grub2-mkstandalone -l format -d 'Generate an image in the specified FORMAT.   Valid values are: . RS . RS 4 '
complete -c grub2-mkstandalone -l compression -d 'Use one of xz, none, or auto as the compression method for the core image'
complete -c grub2-mkstandalone -l modules -d 'Pre-load modules specified by MODULES'
complete -c grub2-mkstandalone -l install-modules -d 'Install only MODULES and their dependencies'
complete -c grub2-mkstandalone -l themes -d 'Install THEMES.   The default is to install the starfield theme, if available'
complete -c grub2-mkstandalone -l fonts -d 'Install FONTS.   The default is to install the unicode font'
complete -c grub2-mkstandalone -l locales -d 'Install only locales listed in LOCALES'
complete -c grub2-mkstandalone -l compress -d 'Compress GRUB files using the specified compression algorithm'
complete -c grub2-mkstandalone -l directory -d 'Use images and modules in DIR'
complete -c grub2-mkstandalone -l grub-mkimage -d 'Use FILE as grub-mkimage.   The default is /usr/bin/grub-mkimage'

