# grub2-glue-efi
# Autogenerated from man page /usr/share/man/man1/grub2-glue-efi.1.gz
complete -c grub2-glue-efi -l input32 -d 'Read 32-bit binary from FILE'
complete -c grub2-glue-efi -l input64 -d 'Read 64-bit binary from FILE'
complete -c grub2-glue-efi -l output -d 'Write resulting fat binary to FILE'
complete -c grub2-glue-efi -l verbose -d 'Print verbose messages'

