# grub2-macbless
# Autogenerated from man page /usr/share/man/man8/grub2-macbless.8.gz
complete -c grub2-macbless -l ppc -d 'Bless the file for use on PPC-based Macs'
complete -c grub2-macbless -l verbose -d 'Print verbose messages'
complete -c grub2-macbless -l x86 -d 'Bless the file for use on x86-based Macs'

