# grub2-mkconfig
# Autogenerated from man page /usr/share/man/man8/grub2-mkconfig.8.gz
complete -c grub2-mkconfig -l output -d 'Write generated output to FILE'
complete -c grub2-mkconfig -l no-grubenv-update -d 'Do not update variables in the grubenv file'

