# grub2-bios-setup
# Autogenerated from man page /usr/share/man/man8/grub2-bios-setup.8.gz
complete -c grub2-bios-setup -l allow-floppy -d 'Make the device also bootable as a floppy'
complete -c grub2-bios-setup -l boot-image -d 'Use FILE as the boot image.   The default value is boot. img'
complete -c grub2-bios-setup -l core-image -d 'Use FILE as ther core image.   The default value is core. img'
complete -c grub2-bios-setup -l directory -d 'Use GRUB files in the directory DIR.   The default value is /boot/grub'
complete -c grub2-bios-setup -l force -d 'Install even if problems are detected'
complete -c grub2-bios-setup -l device-map -d 'Use FILE as the device map.   The default value is /boot/grub/device. map '
complete -c grub2-bios-setup -l skip-fs-probe -d 'Do not probe DEVICE for filesystems'
complete -c grub2-bios-setup -l verbose -d 'Print verbose messages'

