# grub2-mkfont
# Autogenerated from man page /usr/share/man/man1/grub2-mkfont.1.gz
complete -c grub2-mkfont -l ascii-bitmaps -d 'Save only bitmaps for ASCII characters'
complete -c grub2-mkfont -l force-autohint -d 'Force generation of automatic hinting'
complete -c grub2-mkfont -l bold -d 'Convert font to bold'
complete -c grub2-mkfont -l asce -d 'Set font ascent to NUM'
complete -c grub2-mkfont -l desc -d 'Set font descent to NUM'
complete -c grub2-mkfont -l index -d 'Select face index NUM'
complete -c grub2-mkfont -l name -d 'Set font family to NAME'
complete -c grub2-mkfont -l no-bitmap -d 'Ignore bitmap strikes when loading'
complete -c grub2-mkfont -l no-hinting -d 'Disable hinting'
complete -c grub2-mkfont -l output -d 'Save ouptut to FILE.   This argument is required'
complete -c grub2-mkfont -l range -d 'Set the font ranges to each pair of FROM,TO'
complete -c grub2-mkfont -l size -d 'Set font size to SIZE'
complete -c grub2-mkfont -l verbose -d 'Print verbose messages'
complete -c grub2-mkfont -l width-spec -d 'Create a width summary file'

