# grub2-syslinux2cfg
# Autogenerated from man page /usr/share/man/man1/grub2-syslinux2cfg.1.gz
complete -c grub2-syslinux2cfg -l cwd -d 'Set DIR as syslinux\'s working directory'
complete -c grub2-syslinux2cfg -l root -d 'Set DIR as the root directory of the syslinux disk'
complete -c grub2-syslinux2cfg -l verbose -d 'Print verbose messages'
complete -c grub2-syslinux2cfg -l target-root -d 'Root directory as it will be seen at runtime.   The default value is "/"'
complete -c grub2-syslinux2cfg -l target-cwd -d 'Working directory of syslinux as it will be seen at runtime'
complete -c grub2-syslinux2cfg -l output -d 'Write the new config file to FILE.   The default value is standard output'
complete -c grub2-syslinux2cfg -l isolinux -d 'Assume that the input file is an isolinux configuration file'
complete -c grub2-syslinux2cfg -l pxelinux -d 'Assume that the input file is a pxelinux configuration file'
complete -c grub2-syslinux2cfg -l syslinux -d 'Assume that the input file is a syslinux configuration file'

