# grub2-switch-to-blscfg
# Autogenerated from man page /usr/share/man/man8/grub2-switch-to-blscfg.8.gz
complete -c grub2-switch-to-blscfg -l grub-directory -d 'Search for grub. cfg under DIR'
complete -c grub2-switch-to-blscfg -l config-file -d 'The grub config file to use.   The default value is /etc/grub2-efi'
complete -c grub2-switch-to-blscfg -l grub-defaults -d 'The defaults file for grub-mkconfig.   The default value is /etc/default/grub'
complete -c grub2-switch-to-blscfg -l bls-directory -d 'Create BootLoaderSpec fragments in DIR'
complete -c grub2-switch-to-blscfg -l backup-suffix -d 'The suffix to use for saved backup files.   The default value is . bak'

