# grub2-mkimage
# Autogenerated from man page /usr/share/man/man1/grub2-mkimage.1.gz
complete -c grub2-mkimage -l config -d 'Embed FILE as the image\'s initial configuration file'
complete -c grub2-mkimage -l compression -d 'Use one of xz, none, or auto as the compression method for the core image'
complete -c grub2-mkimage -l directory -d 'Use images and modules from DIR'
complete -c grub2-mkimage -l pubkey -d 'Embed the public key FILE for signature checking'
complete -c grub2-mkimage -l memdisk -d 'Embed the memdisk image FILE'
complete -c grub2-mkimage -l note -d 'Add a CHRP NOTE section.   This option is only valid on IEEE1275 platforms'
complete -c grub2-mkimage -l output -d 'Write the generated file to FILE'
complete -c grub2-mkimage -l format -d 'Generate an image in the specified FORMAT.   Valid values are: . RS . RS 4 '
complete -c grub2-mkimage -l prefix -d 'Set prefix directory.   The default value is /boot/grub'
complete -c grub2-mkimage -l verbose -d 'Print verbose messages'

