# grub2-mkpasswd-pbkdf2
# Autogenerated from man page /usr/share/man/man1/grub2-mkpasswd-pbkdf2.1.gz
complete -c grub2-mkpasswd-pbkdf2 -l iteration-count -d 'Number of PBKDF2 iterations'
complete -c grub2-mkpasswd-pbkdf2 -l buflen -d 'Length of generated hash'
complete -c grub2-mkpasswd-pbkdf2 -l salt -d 'Length of salt to use'

