# grub2-render-label
# Autogenerated from man page /usr/share/man/man1/grub2-render-label.1.gz
complete -c grub2-render-label -l color -d 'Use COLOR as the color for generated labels'
complete -c grub2-render-label -l bgcolor -d 'Use COLOR as the background color for generated labels'
complete -c grub2-render-label -l font -d 'Use FILE as the font file for generated labels'
complete -c grub2-render-label -l input -d 'Read input text from FILE'
complete -c grub2-render-label -l output -d 'Render output to FILE'
complete -c grub2-render-label -l text -d 'Use STRING as input text'
complete -c grub2-render-label -l verbose -d 'Print verbose output.  SEE ALSO info grub'

