# grub2-fstest
# Autogenerated from man page /usr/share/man/man1/grub2-fstest.1.gz
complete -c grub2-fstest -l diskcount -d 'Specify the number of input files'
complete -c grub2-fstest -l crypto -d 'Mount cryptographic devices'
complete -c grub2-fstest -l debug -d 'Set debug environment variable'
complete -c grub2-fstest -l zfs-key -d 'Load ZFS cryptographic key'
complete -c grub2-fstest -l length -d 'Handle NUM bytes in output file'
complete -c grub2-fstest -l root -d 'Set root device'
complete -c grub2-fstest -l skip -d 'Skip NUM bytes from output file'
complete -c grub2-fstest -l uncompress -d 'Uncompress data'
complete -c grub2-fstest -l verbose -d 'Print verbose messages'

